<?php

namespace AppBundle\Repository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    const MAX_RESULTS = 15;

    public function getBlogPaginator($page, $category = null)
    {
        $qb =$this->getBlogQb($page);

        if ($category) {
            $qb->andWhere('(b.category = :category )')
                ->setParameter('category', $category);
        }

        return new Paginator($qb, false);
    }

    public function getBlogQb($page)
    {
        --$page;
        return $this->createQueryBuilder('b')
            ->andWhere('b.isPublished = 1')
            ->addOrderBy('b.publishedAt', 'DESC')
            ->setMaxResults(self::MAX_RESULTS)
            ->setFirstResult($page*self::MAX_RESULTS);
    }

    public function getLatest($category = 'cartoon')
    {
        return $this->createQueryBuilder('b')
            ->andWhere("NOT EXISTS (select * from post p where p.isPublished=true and p.category='$category' p.id > b.id)")
            ->getQuery()->getResult();
    }

    public function getNeighbours($id, $category = 'cartoon')
    {
        $previous = $this->getEntityManager()->createQuery("SELECT max(p.id) as id FROM AppBundle:Post p where p.isPublished = TRUE and p.category='$category' and p.id < $id")->getSingleScalarResult();
        $next     = $this->getEntityManager()->createQuery("SELECT min(p.id) as id FROM AppBundle:Post p where p.isPublished = TRUE and p.category='$category' and p.id > $id")->getSingleScalarResult();

        return ['previous' => $previous, 'next' => $next];
    }

    public function getRandom($category = 'cartoon')
    {
        return null;
    }
}
