app:
    resource: "@AppBundle/Controller/"
    type:     annotation

about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/about.html.twig

contact:
    path: /contact
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/contact.html.twig

also_of_interest:
    path: /also-of-interest
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/also-of-interest.html.twig

about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/jazz.html.twig


game_snake:
    path: /games/snake
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    pages/snake.html.twig

game_sudoku_solver:
    path: /games/sudoku-solver
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    pages/sudoku.html.twig

game_mandelbrot:
    path: /games/mandelbrot
    defaults:
        _controller: FrameworkBundle:Template:template
        template: pages/mandelbrot.html.twig

game_metaball:
    path: /games/metaball
    defaults:
        _controller: FrameworkBundle:Template:template
        template: pages/metaball.html.twig

game_test:
    path: /games/test
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    pages/test.html.twig

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"