app:
    resource: "@AppBundle/Controller/"
    type:     annotation

about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/about.html.twig

professional:
    path: /professional
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/professional.html.twig

contact:
    path: /contact
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/contact.html.twig

also_of_interest:
    path: /also-of-interest
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/also-of-interest.html.twig

jazz:
    path: /jazz
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/jazz.html.twig

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"