app:
    resource: "@AppBundle/Controller/"
    type:     annotation

homepage:
    path: /
    defaults:
        _controller: AppBundle:Default:list

about:
    path: /about
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/about.html.twig

contact:
    path: /contact
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/contact.html.twig

also_of_interest:
    path: /also-of-interest
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    static/also-of-interest.html.twig

space_invaders:
    path: /space-invaders
    defaults:
        _controller: FrameworkBundle:Template:template
        template:    default/space-invaders.html.twig

# app/config/routing.yml
fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"